export const LETTER_CARDS = [
  { id: "A", upper: "A", lower: "a", word: "Apple", icon: "🍎", color: "#e53935", desc: "A for Apple!" },
  { id: "B", upper: "B", lower: "b", word: "Bear", icon: "🐻", color: "#8d6e63", desc: "B for Bear!" },
  { id: "C", upper: "C", lower: "c", word: "Cat", icon: "🐱", color: "#ffb300", desc: "C for Cat!" },
  { id: "D", upper: "D", lower: "d", word: "Dog", icon: "🐶", color: "#795548", desc: "D for Dog!" },
  { id: "E", upper: "E", lower: "e", word: "Elephant", icon: "🐘", color: "#78909c", desc: "E for Elephant!" },
  { id: "F", upper: "F", lower: "f", word: "Frog", icon: "🐸", color: "#43a047", desc: "F for Frog!" },
  { id: "G", upper: "G", lower: "g", word: "Giraffe", icon: "🦒", color: "#fdd835", desc: "G for Giraffe!" },
  { id: "H", upper: "H", lower: "h", word: "House", icon: "🏠", color: "#00acc1", desc: "H for House!" },
  { id: "I", upper: "I", lower: "i", word: "Ice Cream", icon: "🍦", color: "#f48fb1", desc: "I for Ice Cream!" },
  { id: "J", upper: "J", lower: "j", word: "Juice", icon: "🧃", color: "#4caf50", desc: "J for Juice!" },
  { id: "K", upper: "K", lower: "k", word: "Kite", icon: "🪁", color: "#f44336", desc: "K for Kite!" },
  { id: "L", upper: "L", lower: "l", word: "Lion", icon: "🦁", color: "#ffa000", desc: "L for Lion!" },
  { id: "M", upper: "M", lower: "m", word: "Monkey", icon: "🐒", color: "#8d6e63", desc: "M for Monkey!" },
  { id: "N", upper: "N", lower: "n", word: "Nest", icon: "🪹", color: "#5d4037", desc: "N for Nest!" },
  { id: "O", upper: "O", lower: "o", word: "Owl", icon: "🦉", color: "#3e2723", desc: "O for Owl!" },
  { id: "P", upper: "P", lower: "p", word: "Pig", icon: "🐷", color: "#f48fb1", desc: "P for Pig!" },
  { id: "Q", upper: "Q", lower: "q", word: "Queen", icon: "👑", color: "#ffd54f", desc: "Q for Queen!" },
  { id: "R", upper: "R", lower: "r", word: "Rabbit", icon: "🐰", color: "#9e9e9e", desc: "R for Rabbit!" },
  { id: "S", upper: "S", lower: "s", word: "Sun", icon: "☀️", color: "#ffeb3b", desc: "S for Sun!" },
  { id: "T", upper: "T", lower: "t", word: "Tiger", icon: "🐯", color: "#fb8c00", desc: "T for Tiger!" },
  { id: "U", upper: "U", lower: "u", word: "Umbrella", icon: "☔", color: "#9c27b0", desc: "U for Umbrella!" },
  { id: "V", upper: "V", lower: "v", word: "Van", icon: "🚐", color: "#2196f3", desc: "V for Van!" },
  { id: "W", upper: "W", lower: "w", word: "Whale", icon: "🐳", color: "#03a9f4", desc: "W for Whale!" },
  { id: "X", upper: "X", lower: "x", word: "Xylophone", icon: "🎹", color: "#ff5722", desc: "X for Xylophone!" },
  { id: "Y", upper: "Y", lower: "y", word: "Yoyo", icon: "🪀", color: "#e91e63", desc: "Y for Yoyo!" },
  { id: "Z", upper: "Z", lower: "z", word: "Zebra", icon: "🦓", color: "#212121", desc: "Z for Zebra!" },
];

export const NUMBER_CARDS = [
  { id: "1", num: "1", word: "One Apple", icon: "🍎", color: "#e53935", desc: "One!" },
  { id: "2", num: "2", word: "Two Cats", icon: "🐱🐱", color: "#ffb300", desc: "Two!" },
  { id: "3", num: "3", word: "Three Stars", icon: "⭐⭐⭐", color: "#fdd835", desc: "Three!" },
  { id: "4", num: "4", word: "Four Dogs", icon: "🐶🐶🐶🐶", color: "#8d6e63", desc: "Four!" },
  { id: "5", num: "5", word: "Five Cars", icon: "🚗🚗🚗🚗🚗", color: "#1e88e5", desc: "Five!" },
  { id: "6", num: "6", word: "Six Balloons", icon: "🎈🎈🎈🎈🎈🎈", color: "#e53935", desc: "Six!" },
  { id: "7", num: "7", word: "Seven Trees", icon: "🌳🌳🌳🌳🌳🌳🌳", color: "#43a047", desc: "Seven!" },
  { id: "8", num: "8", word: "Eight Flowers", icon: "🌸🌸🌸🌸🌸🌸🌸🌸", color: "#f48fb1", desc: "Eight!" },
  { id: "9", num: "9", word: "Nine Fish", icon: "🐟🐟🐟🐟🐟🐟🐟🐟🐟", color: "#03a9f4", desc: "Nine!" },
  { id: "10", num: "10", word: "Ten Blocks", icon: "🧱🧱🧱🧱🧱🧱🧱🧱🧱🧱", color: "#ff9800", desc: "Ten!" },
];

export const COLOR_CARDS = [
  { id: "red", colorName: "Red", word: "Red Apple", icon: "🍎", color: "#e53935", desc: "Red!" },
  { id: "blue", colorName: "Blue", word: "Blue Whale", icon: "🐳", color: "#1e88e5", desc: "Blue!" },
  { id: "green", colorName: "Green", word: "Green Frog", icon: "🐸", color: "#43a047", desc: "Green!" },
  { id: "yellow", colorName: "Yellow", word: "Yellow Sun", icon: "☀️", color: "#fdd835", desc: "Yellow!" },
  { id: "orange", colorName: "Orange", word: "Orange", icon: "🍊", color: "#ff9800", desc: "Orange!" },
  { id: "purple", colorName: "Purple", word: "Purple Grapes", icon: "🍇", color: "#8e24aa", desc: "Purple!" },
  { id: "pink", colorName: "Pink", word: "Pink Pig", icon: "🐷", color: "#f48fb1", desc: "Pink!" },
  { id: "brown", colorName: "Brown", word: "Brown Bear", icon: "🐻", color: "#795548", desc: "Brown!" },
  { id: "black", colorName: "Black", word: "Black Cat", icon: "🐈‍⬛", color: "#212121", desc: "Black!" },
  { id: "white", colorName: "White", word: "White Cloud", icon: "☁️", color: "#9e9e9e", desc: "White!" },
];
